services:
  app:
    build: .
    container_name: undangan_nikahan_app
    restart: always
    environment:
      - VIRTUAL_HOST=undangan.yourdomain.com
      - LETSENCRYPT_HOST=undangan.yourdomain.com
      - LETSENCRYPT_EMAIL=your@email.com
    env_file:
      - ./src/.env
    volumes:
      - ./src/storage:/var/www/html/storage
      - ./src/database:/var/www/html/database
    networks:
      - webapps

networks:
  webapps:
    external: true
